include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Переопределение уровней важности
    invalid_annotation_target: ignore
    unnecessary_this: warning
    dead_code: warning
    unused_local_variable: warning # todo: error
    unused_import: warning         # todo: error
    missing_required_param: error
    missing_return: error
    avoid_relative_lib_imports: warning
    always_use_package_imports: warning # todo: error
    non_constant_identifier_names: error
    cast_nullable_to_non_nullable: error
    duplicate_import: error
    must_call_super: error
    invalid_use_of_visible_for_testing_member: error
    unused_catch_stack: warning
    invalid_null_aware_operator: error
    dead_null_aware_expression: error
    prefer_single_quotes: warning # todo: error
    unused_field: warning         # todo: error

  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/*.gql.dart'
    - '**/*.graphql.dart'
    - '**/*.graphql'
    - 'demo/**'
    - '**/bottom_sheet.dart'
    - '**/sheet.dart'
    - '**/scrolling.dart'

linter:
  rules:
    # Импорты
    avoid_relative_lib_imports: true
    always_use_package_imports: true

    # Чистота и читаемость
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    unnecessary_statements: true
    empty_statements: true
    empty_constructor_bodies: true

    # Конвенции именования
    camel_case_types: true
    camel_case_extensions: true
    constant_identifier_names: true
    non_constant_identifier_names: true
    library_prefixes: true

    # Порядок и оформление
    sort_constructors_first: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    directives_ordering: true
    file_names: true
    eol_at_end_of_file: true

    # Стиль
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_is_not_empty: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_typing_uninitialized_variables: true
    always_declare_return_types: true
    always_specify_types: false # см. incompatibility
    omit_local_variable_types: true
    prefer_inlined_adds: true
    prefer_function_declarations_over_variables: true

    # Безопасность и надёжность
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    only_throw_errors: true
    cancel_subscriptions: true
    close_sinks: true
    use_super_parameters: true
    unawaited_futures: true

    # Лучшие практики
    use_colored_box: true
    use_decorated_box: true
    prefer_spread_collections: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_adjacent_string_concatenation: true
    cascade_invocations: true
    tighten_type_of_initializing_formals: true
    avoid_returning_null_for_void: true
    avoid_classes_with_only_static_members: true
    avoid_escaping_inner_quotes: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true

    # Flutter & UI
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true

    # RegExp
    valid_regexps: true

    # Паб правила
    depend_on_referenced_packages: true
    package_names: true

    # Дополнительные рекомендации
    use_function_type_syntax_for_parameters: true
    use_named_constants: true
    prefer_mixin: true
    avoid_returning_this: true
    avoid_shadowing_type_parameters: true
    avoid_redundant_argument_values: true
    prefer_initializing_formals: true

    # Те, что часто спорные — отключены
    avoid_final_parameters: false
    library_private_types_in_public_api: false
    avoid_positional_boolean_parameters: false
    control_flow_in_finally: true
    annotate_overrides: true
