name: test_dayly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ui_kit:
    path: ./packages/ui_kit
  presentation:
    path: ./packages/presentation
  domain:
    path: ./packages/domain
  data:
    path: ./packages/data
  assets:
    path: ./packages/assets
  core:
    path: ./packages/core
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true