name: presentation
description: UI Kit package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.3.0
  freezed_annotation: ^3.1.0
  core:
    path: ../core
  flutter_svg: ^2.2.1
  assets:
    path: ../assets
  ui_kit:
    path: ../ui_kit
  domain:  
    path: ../domain
  modal_bottom_sheet: ^3.0.0
  two_dimensional_scrollables: ^0.3.7
dev_dependencies:
  build_runner: ^2.10.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter:
  uses-material-design: true
